---
title: "Data Science Depot: Home"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Data Science Depot is a collection of data science articles I've written as part of my participation in the Data Science Community on Coursera.org.

## Data Science Careers

Articles in this section cover responses to community members' questions about how to start or grow a career in Data Science.

## Interviewing Techniques

1. [Answering Questions about an Unfamiliar Domain](http://bit.ly/2oKYQZS)

## Guidelines for Science

Content in this section is related to Armstrong (2016) et. al. paper and presentation helping people distinguish true "science" from political / policy advocacy. 

1. [2016 Presentation: Improving Management Science -- Problems and Solutions](http://bit.ly/2pPIv7A) PDF version of presentation given at 2016 Marketing conference in Hong Kong.  
2. [2016 Paper: Improving Management Science -- Problems and Solutions](http://bit.ly/2ofV27c) Full length version of the paper discussed in the above presentation. PDF version of the paper is also available on researchgate.net. Stored here because these references have a tendency to disappear from the internet over time.
3. [Guidelines for Science: Checklist](http://bit.ly/2pQQUuB) Checklist that can be used to evaluate whether a research paper is truly science, or advocacy disguised as science. 

## Future of Data Analysis / John Tukey Retrospective

1. [The Future of Data Analysis](http://bit.ly/2uC9atX) by John Tukey, 1962 paper where he challenges statisticians to move away from ever more complicated mathematics to tackle data analysis problems in more realistic ways. 
2. [50 Years of Data Science](http://bit.ly/2tKcaQu) by David Donoho, a 2015 retrospective on John Tukey's 1962 paper. 


## Statistical Methods

1. [Statistical Methods in Psychology Journals](http://bit.ly/2fciQWx) Classic 1999  article by [Leland Wilkinson](http://bit.ly/2fciQWx) and the Task Force on Statistical Inference for the American Psychology Association. 
2. [Ordinal Independent Variables in Linear Regression](http://bit.ly/2fd9f1E) Article by Richard Williams at the University of Notre Dame, making the argument to treat ordinal variables as continuous unless the analysis of linear effects indicates they should be treated as nominal level of measurement. 

# Johns Hopkins Data Science Specialization

Articles in this section are related to the 10 course Data Science Specialiazation that is offered by Johns Hopkins University via Coursera. An analysis of the specialization, [The democratization of data science education](http://bit.ly/2y6ePGy), was published during the summer of 2017. 

## Course 1: Data Scientist's Toolbox

1. [Course Prerequisites and Difficulty Levels](http://bit.ly/2e6y3nn) Provides an overview of the Data Science Specialization courses, explaining from a practical perspective the courses a student needs as prerequisites to other courses. While students may take more than one class at a time, it's important to know how information from earlier courses is used in subsequent ones. <br><br> The article also ranks the difficulty levels from most to least difficult, based on the author's experience in the curriculum as well as Discussion Forum feedback contributed by other students.
1. [Configuring RStudio to work with git / github - Mac OSX](http://bit.ly/2c9Q2bf)
2.  [Configuring RStudio to work with git / github - Windows 7, 8, and 10](http://bit.ly/2bPxOL5)
3. [Using Editor Modes in Discussion Forum Posts](http://bit.ly/2j4f1iX)
4. [Buying a Computer for Data Science](http://bit.ly/2bHgwAY)
5. [R and RStudio on Chromebook](http://bit.ly/2eQ8ipJ)

### Issue: Students Struggle to find URLs in Lecture Slides

If you're interested in the URLs for the lecture slides, they are available in the [Data Science Specialization Courses](http://bit.ly/2bJcXNW) github repository. Each course is stored in a subdirectory within the repository, and the slides are built in R Markdown language, a technique you'll learn in *Developing Data Products*.

## Course 2: R Programming

### START HERE

If you're new to the course and trying to figure out what to do in what order, start with these articles.

1. [Resources for R Programming](http://bit.ly/2dhZ8Dy) Provides a summary of student-generated content to support the course, some of which is indexed on the [Data Science Specialization's github.io](http://datasciencespecialization.github.io/) site
2. [References for R Programming](http://bit.ly/2b8AxhF) Provides a list of references for R programming, ranging from beginning to advanced topics.
3. [Data Science Specialization: what is the value?](http://bit.ly/2j3EcCn) Addresses a common question raised by students in *R Programming* who are frustrated by the amount of work they have to do on their own to complete quizzes and assignments. 
4. [R versus Python](http://bit.ly/2kleU76) Roundup of articles and surveys comparing R and Python, including usage, history, and pros / cons. 

The next set of articles includes general commentary about the course, R programming in general, and R in relationship to other statistics packages.

1. [Commercial Statistics Packages: An Historical Perspective](http://bit.ly/2fPj2qN)
2. [Configuring RStudio to work with git / github - Mac OSX](http://bit.ly/2c9Q2bf)
2. [A Data Frame is Also a List](http://bit.ly/2fmMRAp)
2. [Forms of the Assignment  Operator](http://bit.ly/2dtPhM9)
2. [Forms of the Extract Operator](http://bit.ly/2bzLYTL)
3. [S Objects, R Objects, and Lexical Scoping](http://bit.ly/2dtOSXi)
3. [Thinking in R versus Thinking in SAS](http://bit.ly/2cH3u8x)
3. [Strategy for the Programming Assignments](http://bit.ly/2ddFh9A)
3. [Why is R More Difficult than SAS?](http://bit.ly/2erxk3A)
4. [R Onboarding for SAS Users](http://bit.ly/2dr7yum)
5. [References for R Programming](http://bit.ly/2b8AxhF) Provides a list of references for R programming, ranging from beginning to advanced topics.
6. [Object Oriented Programming and R](http://bit.ly/2f5lzyh) Explains how object oriented programming concepts are implemented in R, in response to a student question about accessing content output by the R linear models function, `lm()`.
7. [Scoping in C/C++ vs. R](http://bit.ly/2l9tTAx) Compares variable scoping in R versus C/C++. 

### Posts regarding specifics of programming assignments

1. [Assignment 1: Breaking Down Pollutantmean](http://bit.ly/2cHyiCl)
2. [Assignment 1: A SAS Version of  Pollutantmean](http://bit.ly/2d3DR4e)
3. [Assignment 1: Common Mistakes - Weighted vs. Unweighted Means](http://bit.ly/2cA0fSh)
4. [Assignment 1: A More Elegant Solution](http://bit.ly/2kwBBlK)
4. [Assignment 2: Demystifying makeVector](http://bit.ly/2bTXXfq)
1. [Assignment 2: makeCacheMatrix as an Object](http://bit.ly/2byUe4e)
4. [Assignment 2: Using Github Desktop](http://bit.ly/2udIoFf)
2. [Assignment 2: Grading the SHA-1 Hash Code](http://bit.ly/2iUWoB6)
3. [Assignment 3: Functions to Sort Data Frames](http://bit.ly/2dxItzw)

### Miscellaneous Code Examples and Instructions

1. [Permanently Setting R Working Directory](http://www.r-bloggers.com/setting-your-working-directory-permanently-in-r/) Link to R-bloggers.com article that explains how to set your working directory permanently in R (instead of RStudio)
2. [Tutorial: Downloading Files](http://bit.ly/2iP2suj) Illustrates various ways of downloading files, including binary and text files. 
3. [Creative Use of R: Downloading Course Lectures](http://bit.ly/2bGlI7R) Article illustrating how to use R to automate the download of lectures from *Data Science Specialization* courses, such as *R Programming*. Techniques used in this article are helpful to make research reproducible, as required for courses like *Getting and Cleaning Data* and *Reproducible Research*.
4. [How to Upgrade R without Losing Your Packages](http://bit.ly/2ejS8ox) article by Kris Eberwein on datascienceriot.com that includes code to save your list of packages to an rds file, and reinstall any packages that don't make it through the upgrade process.
5. [Common R Mistakes: Overwriting R Functions with Output Variables](http://bit.ly/2i3gmoA)  
6. [R Programming Cheat Sheet](http://bit.ly/2rwY4CD) Based on content from *R for Everyone* by Jared Lander. 

### Interesting R News and Blog Articles

1. [R vs. Python: 2016 Survey of Software used for Data Science](http://bit.ly/2b827ey) Overview of results from a 2016 KDNuggets Software Poll, written by Gregory Piatetsky. The follow up article with expanded analysis is [What Big Data, Data Science, Deep Learning software goes together](http://bit.ly/2bFBPmW), also on [kdnuggets.com](http://bit.ly/2b83GcK).
2. [R and Python vs. SAS and SPSS](http://bit.ly/2mJ3l6X) Jeroen Kromme's take on strengths and weaknesses of these languages, posted on [r-bloggers.com](http://r-bloggers.com). 
2. [Scaling R for Data Science](http://oreil.ly/2b8pQyR) August 2016 article by Federico Castanedo explaining three ways to scale R.  
3. [Lexical Scoping and Statistical Computing](http://bit.ly/2cmqAPy) Article by Robert Gentleman and Ross Ihaka at the University of Auckland describing how lexical scoping works, and why it is valuable in statistical computing.
4. [Data Science Job Report 2017: R Passes SAS, But Python Leaves Them Both Behind](http://bit.ly/2oCHulX) Bob Muenchen's take on the job market for various data science langauges. 

## Course 3: Getting and Cleaning Data

1. [Real World Example: Reading American Community Survey data](http://bit.ly/2bAdLE9) Illustrates concepts covered in *Getting and Cleaning Data* with U.S. Census data, including how to process a hierarchical file format in R, as well as using an electronic codebook to generate the parameters required to read the data file into a data frame.
2. [Common Problems: Quiz 1 - Missing Java Runtime](http://bit.ly/2jjtyXM) Explains how to solve the problem of a missing Java Runtime for the question that requires students to process a Microsoft Excel spreadsheet. 
3. [Strategy for Reading Files & APIs / Quiz 2](http://bit.ly/2e4L5oF)
4. [Common Problems: Quiz 2 - sqldf() driver fails to connect](http://bit.ly/2kD2KTY)

### Articles and Content Related to Getting and Cleaning Data

1. [Tidy Data](http://bit.ly/2nyw5Ci) Hadley Wickham's paper on Tidy Data, required reading for the course project. 
2. [data.table Github Wiki](http://bit.ly/2og7rDK) Repository for `data.table` package, including video. 
3. [Tutorial: Downloading Files](http://bit.ly/2iP2suj) Illustrates various ways of downloading files, including binary and text files. 

## Course 4: Exploratory Data Analysis

1. [Assignment 1: Reading a Subset of Raw Data](http://bit.ly/2oAHoqI)


## Course 5: Reproducible Research
1. [Assignment 2 Checklist](http://bit.ly/2c6XFhQ)
2. [Configuring knitr to Retain Markdown Output](http://bit.ly/2nITVJH) Explains how to configure knitr so that markdown file and any associated graphics are retained after building an HTML document, so they can be uploaded to Github and viewed there. 
3. [Assignment 2: Improving Runtime Performance of Initial Data Load](http://bit.ly/2q0ieCO)

## Course 6: Statistical Inference

1. [Reference Materials for Statistical Inference](http://bit.ly/2c50sKo)  Start here if you're looking for help on the statistical techniques taught in this course.
4. [Using MathJax with Discussion Forums, R Markdown, and Github Pages](http://bit.ly/2doF4OT)
4. [Poisson Confidence Interval Explained](http://bit.ly/2m8qQ8y) Explains the formulas on slide 26 of the *Asymptopia* lecture, illustrates the differences in two calculations on slide 27. 
5. [Power Calculations: Optimal Sample size](http://bit.ly/2i1RDGa)
6. [Permutation Tests Explained](http://bit.ly/2iV2HEx)


### Articles Related to the Course Project

1. [Exponential Distribution / Central Limit Theorem - Assignment Checklist](http://bit.ly/2i5v81c)
2. [ToothGrowth Analysis - Assignment Checklist](http://bit.ly/2iP39Ur)
3. [Exploratory Data Analysis in ToothGrowth Assignment](http://bit.ly/2iQEfBV), explaining the exploratory data analysis requirement for students who have not taken the *Exploratory Data Analysis* course prior to taking *Statistical Inference*.
4. [Accessing R Code from an Appendix in Knitr](http://bit.ly/2i1I0XW)
5. [Theoretical Variance of Sampling Distribution of the Mean](http://bit.ly/2iPa2oz)
6. [Kable Tables with Data Frames](http://bit.ly/2j40Wlw) illustrates how to display a custom table in a `knitr()` document by creating a data frame to contain the information to be rendered with `kable()`.
7. [Installing MiKTeX on Windows 10 / Generating a PDF with knitr](http://bit.ly/2iiGNbu)
8. [Commentary on Factorial Design in Toothgrowth Analysis](http://bit.ly/2eEVRhw) Illustrates how to conduct a full factorial analysis of variance with the toothgrowth data, comparing it to the techniques used in the course project for *Statistical Inference*. 

## Course 7: Regression Models

1. [Why does sum of errors * X equal 0?](http://bit.ly/2ipyoSN)
2. [Using MathJax with Discussion Forums, R Markdown, and Github Pages](http://bit.ly/2doF4OT)


## Course 8: Practical Machine Learning
1. [Week 4: Combining Predictors Math Explained](http://bit.ly/2i5z0Q4)
2. [Course Project - gh-pages Setup with RStudio](http://bit.ly/2bTvGqr)
2. [Course Project - Improving Runtime Performance of Random Forest Models with caret::train()](http://bit.ly/2bYtutG)
2. [Course Project - Predicting Test Scores based on Training Model Accuracy](http://bit.ly/2i5A3zx)

## Course 9: Developing Data Products
1. [Configuring shinyapps.io Application Timeout](http://bit.ly/2dEq8O8) A walkthrough on how to configure a Shiny application so it doesn't waste the free monthly server processing time.

## Course 10: Capstone
1. [Speech and Language Processing, 3rd Edition](https://web.stanford.edu/~jurafsky/slp3/) Working version of Jurafsky, et. al. book on natural language processing whose content on n-grams is helpful for the capstone.
2. [n-gram Computations and Computer Capacity](http://bit.ly/2couvxh) Explains the amount of memory required to convert the text files for the course project into n-grams, using the <strong>quanteda</strong> package.
3. [Capstone Strategy](http://bit.ly/2rGcgc6) Describes a general strategy to get through the Capstone: use the simplest approaches possible.
4. [Choosing a Text Analysis Package](http://bit.ly/2qagsPa) Reviews pros and cons of various R packages used for natural language processing, in the context of requirements for the Capstone project. 

## Content for Community Mentors
1. [Tips for New Community Mentors](http://bit.ly/2bZJniM) A list of tips for new mentors supporting the *Data Science Specialization*, ranging from when to direct students to paid / professional resources such as the *Coursera Learner Help Center*, to how to optimize the value of content that is posted by mentors.
